name = "thebookofyourlife"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "thebookofyourlife-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
